baseURL = 'https://blog.misilelaboratory.xyz'
languageCode = 'ko-kr'
title = '404 Not Found'
theme = 'terminal'

[params]
    contentTypeName = "posts"
    themeColor = "blue"
    showMenuItems = 2
    fullWidthTheme = false
    centerTheme = false

[languages]
    [languages.en]
    title = "404 Not Found"
    subtitle = "Maybe found"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
        logoText = "MisileLaboratory"
        logoHomeLink = "/"

    # [languages.en.menu]
      # [[languages.en.menu.main]]
        # identifier = "about"
        # name = "About"
        # url = "/about"
